#!/bin/sh
#
# Mksrc - make illumos source files for /proc-based lsof
#
# WARNING: This script assumes it is running from the main directory
#	   of the lsof, version 4 distribution.
#
# One environment variable applies:
#
# LSOF_MKC	is the method for creating the source files.
#		It defaults to "ln -s".  A common alternative is "cp".
#
# $Id: Mksrc,v 1.2 2000/12/04 14:31:02 abe Exp $


D=dialects/illumos
L="dlsof.h dproc.c dmnt.c dsock.c dfile.c dproto.h dstore.c machine.h"

for i in $L
do
  rm -f $i
  $LSOF_MKC $D/$i $i
  echo "$LSOF_MKC $D/$i $i"
done

